# Nom de l'application
spring.application.name=backend

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/PFA_f
spring.datasource.username=postgres
spring.datasource.password=marwa123
spring.datasource.driver-class-name=org.postgresql.Driver


# Désactiver la sécurité Spring par défaut (facultatif, pour tests)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Format des dates
spring.jackson.time-zone=UTC
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss


# Validation
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
spring.jackson.property-naming-strategy=SNAKE_CASE
#spring.jpa.properties.hibernate.type_contributors=\
  com.mon_projet_pfa.backend.utils.PostgreSQLEnumTypeContributor
  # Pour les enums PostgreSQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false  







